apiVersion: v1
kind: LimitRange
metadata:
  name: dip-limit-range
  namespace: dip-production
spec:
  limits:
    - default:
        cpu: "1000m"
        memory: "1Gi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      type: Container
