apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dip-network-policy
  namespace: dip-production
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: document-intelligence-platform
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: document-intelligence-platform
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - podSelector: {}
