apiVersion: v1
kind: Service
metadata:
  name: dip-api-service
  namespace: dip-production
  labels:
    app.kubernetes.io/name: document-intelligence-platform
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: document-intelligence-platform
    app.kubernetes.io/component: api
