apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: dip-production
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'sre-team-webhook'
    receivers:
      - name: 'sre-team-webhook'
        webhook_configs:
          - url: 'http://alert-receiver.blackrock.internal/api/v1/alerts'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: dip-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: 9093
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: dip-production
spec:
  ports:
    - port: 9093
      name: http
  selector:
    app: alertmanager
