apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: dip-production
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'document-intelligence-api'
        metrics_path: '/api/v1/metrics'
        static_configs:
          - targets: ['dip-api-service:80']

      - job_name: 'opentelemetry-collector'
        static_configs:
          - targets: ['otel-collector-service:8888']
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: dip-production
spec:
  serviceName: prometheus-service
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.52.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
  volumeClaimTemplates:
    - metadata:
        name: prometheus-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: dip-production
spec:
  ports:
    - port: 9090
      name: http
  selector:
    app: prometheus
